comment:
  image:
    repository: mskomorokhova/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: mskomorokhova/post
    tag: latest
  service:
    externalPort: 5000

ui:
  image:
    repository: mskomorokhova/ui
    tag: latest
  service:
    externalPort: 9292
