version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        ipv4_address: 10.0.2.2
  ui:
    build: ../src/ui
    image: ${USERNAME}/ui:${SERVVER}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    ports:
      - 9292:9292/tcp
    networks:
      front_net:
        ipv4_address: 10.0.1.3
  post:
    build: ../src/post-py
    image: ${USERNAME}/post:${SERVVER}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      back_net:
        ipv4_address: 10.0.2.4
      front_net:
        ipv4_address: 10.0.1.4
  comment:
    build: ../src/comment
    image: ${USERNAME}/comment:${SERVVER}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      back_net:
        ipv4_address: 10.0.2.5
      front_net:
        ipv4_address: 10.0.1.5

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${BACKNET}
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${FRONTNET}

